### ISSUE TITLE
Modifying dplython functions to take DataFrame arguments

### ISSUE THREAD

**Issue by dodger487** [dodger487/dplython#12]
I have idea on a change and want to get feedback before making it.

In dplyr, you can call each function on the dataframe itself. So:

``` r
# with piping
df %>% mutate(foo=bar)

# same as
mutate(df, foo=bar)
```

Currently in dplython, the dplython functions all return other functions which are then applied to the DataFrame. If you want to replicate the above, you would have to do something that looks like this:

``` python
# with piping
df >> mutate(foo=X.bar)

# same as
mutate(foo=X.bar)(df)
```

My proposal is to modify the dplython functions to check the type of the first argument. If the first argument is a DataFrame (or inherits from DataFrame), then instead of _returning_ a function, the function _is applied_ to the dataframe. I think this will be more readable.
So:

``` python
# old
mutate(foo=X.bar)(df)

# new, also works
mutate(df, foo=X.bar)
```

Note that this will not break the old way of doing things. I wanted to see what people think before making the change!

**Comment by ngould** [comment]
I like the resulting syntax, but I'm curious why you think type checking is necessary. It seems like what you need to branch on is positional args vs keyword args.

I.e. maybe you could replace this:

```
def mutate(**kwargs):
    # Do the thing
```

With something more like this:

```
def mutate(*args, **kwargs):
    if args:
        df = args[0]
    # Do the thing
```

Thoughts?

**Comment by dodger487** [comment]
That's a nice solution for mutate! Some of the other verbs, like select and dfilter, do use args and not kwargs, so you need to at least check that the input isn't a Later, which might be more efficient than checking if it's a DplyFrame derived class.

**Comment by ngould** [comment]
Ah, gotcha. In that case, I am in favor of your original suggestion. By the way, `isinstance(thing, ThingClass)` is the idiomatic way to do it. The Python hive-mind is generally averse to `type(thing) == ThingClass` for some reason.

**Comment by dodger487** [comment]
This is completed in #14. I ended up using a decorator which does the type check, and then either returns the function or returns the result when the dataframe is piped into the function.

**Comment by danrobinson** [comment]
Great idea. 

One thought: while taking the dataframe as the first argument is the convention in R, the ordinary convention for partial application would generally be to have the dataframe be the _last_ argument. In other words, when a function that requires N arguments is passed fewer arguments, it returns a partially applied function that takes the remaining arguments. 

See [F#](https://fsharpforfunandprofit.com/posts/partial-application/) and [Elm](http://elm-lang.org/docs/syntax#infix-operators) for nice examples of the connection between partial application, infix operators, and pipe operators.

This is probably academic, since in Python, non-keyword arguments can't follow keyword arguments, so this may be impossible to implement (or at least impossible to implement in a non-confusing way). But it may be worth keeping in mind.
