### ISSUE TITLE
Allow group_by on expressions

### ISSUE THREAD

**Issue by danrobinson** [dodger487/dplython#23]
Currently, group_by only works on existing columns, not expressions. For example, `group_by(X.carat + X.price)` seems to only group by X.carat.

Dplyr's [group_by](http://www.inside-r.org/node/230680) allows group_by to be used on expressions.

I think it would make sense if group_by could take named arguments, like `group_by(carat_plus_price=X.carat + X.price)`. This could probably be implemented fairly easily under the hood in group_by by checking for **kwargs and passing them to a mutate() before grouping.

It would be nice if ultimately it could autogenerate a column name, such as "carat_plus_price", if the user does not supply one.

**Comment by dodger487** [comment]
I agree that `group_by` should work on expressions. Also, `arrange` should work on expressions!

dplyr allows named arguments in `group_by`, which is a point in that column. It does strike me as harder to read though and less explicit, instead of a user just doing a `mutate` and then a `group_by`

I think the autogenerated column name is a great idea. I opened issue #24 as a valuable stepping stone for getting there.

**Comment by dodger487** [comment]
This is resolved with #39 and #45
