### ISSUE TITLE
The TestMutates.test_multi test is "theoratically" broken

### ISSUE THREAD

**Issue by Nagasaki45** [dodger487/dplython#5]
I'm working on adding python3 support ([my fork](https://github.com/Nagasaki45/dplython), [travis-ci](https://travis-ci.org/Nagasaki45/dplython/builds)). The only issue I find is the sporadic failures of this specific test.
The reason for the failure is that `pd.DataFrame.equals` compares, between other things, the columns of the data frames. On the other hand, your `mutate` function uses `dict.iteritems` internally to add columns. `dict.iteritems`, by definition, doesn't preserve any order, so there is no way to predict the order of the mutated data frame columns.
I'm not sure what the expected solution will be, but IMHO:
1. Your API is very nice and elegant. I don't think that the `mutate` function signature should be changed, so there is no way to get the columns in order.
2. The `equals` function can be override to be less restrictive.
3. Stop using `equals` in the tests (or at least in this specific test).

Having said that, I didn't notice any failure on python 2.7, but somehow it fails sporadically on python 3.3/4/5.

What do you think?

**Comment by dodger487** [comment]
I think you've uncovered a thorny issue. In Dplyr, the user is able to add a column in a mutate statement derived from a column that he or she just wrote. I want to make this feature available in dplython. So:
`diamonds_dp = self.diamonds >> mutate(foo=X.x, bar=X.foo.mean())`
should be valid. foo should be the first column added, followed by bar. This is difficult to accomplish though as python throws away the order information of **kwargs. Right now, my example code would sometimes work, and sometimes not work depending dictionary ordering. There's a PEP out to accomplish this (https://www.python.org/dev/peps/pep-0468/) but I'll have to look into solutions for right now. 

This issue, however, seems independent of what you're trying to do, which is add Python 3 support. I'm going to open a separate issue for dealing with this problem. For your case, I think you should compare each column across the two dataframes, since we know that the order might not be consistent. If and when we get the keyword ordering fixed we should rewrite the test to again use `equals`

Issue for mutate ordering: https://github.com/dodger487/dplython/issues/6

**Comment by Nagasaki45** [comment]
All right than. I will fix the test and send you a PR for python 3 support.

**Comment by dodger487** [comment]
I think this issue is now encompassed by #6 so I'm going to close this.
