### ISSUE TITLE
group_by mutate do not run per group

### ISSUE THREAD

**Issue by zippeurfou** [dodger487/dplython#91]
Here is a clear example of it
![image](https://user-images.githubusercontent.com/4520383/30933673-3f281ff8-a399-11e7-86b6-35cbced12e4f.png)
You would expect to have 5 different uuid

**Comment by dodger487** [comment]
Hi-- I believe `group_by` with `mutate` is still working as expected (per group). It's a bit confusing, but the code within the mutate definition does not exactly run *per group* unless it uses a "Later" expression. Basically, `uuid.uuid4()` gets called before the mutate gets called, and it thinks you're just inputting a constant (the same UUID) for each group.

If I compute averages by grouped cut, I'll still get five values:
```
In [56]: v = diamonds >> group_by(X.cut) >> mutate(foo = X.x.mean()) >> ungroup() >> select(X.foo)

In [57]: v["foo"].unique()
Out[57]: array([ 5.5074507 ,  5.97388732,  5.83878516,  5.74069608,  6.24689441])
```

How to solve your issue? There are probably a few ways. You can write a function that takes an array of cuts and returns a UUIDs for each cut.
```
@DelayFunction
def generate_uuid(cuts):
    return [uuid.uuid5(uuid.NAMESPACE_OID, c) for c in cuts]

In [68]: v = diamonds >> group_by(X.cut) >> mutate(foo = generate_uuid(X.cut)) >> ungroup() >> select(X.foo)

In [69]: v.foo.unique()
Out[69]:
array([UUID('7b3a35c9-f368-5102-9892-29273936256e'),
       UUID('2fc1427c-09fd-52a1-822e-809ccd700267'),
       UUID('acf56225-2202-532f-a1b4-da549c4e95af'),
       UUID('87529920-ad1b-51ca-9458-4d175dadabe4'),
       UUID('0cc51c30-547b-53ce-af0c-6d40f4cd1ab5')], dtype=object)
```

There's probably a better way to do this that vectorizes the function, so you can write it as if it's taking one string argument instead of a Pandas Series of strings, but I'll leave that for another day.

**Comment by zippeurfou** [comment]
thanks @dodger487 
It is a significant difference with dplyr that I was not aware 👍 
i.e.
![image](https://user-images.githubusercontent.com/4520383/30934726-6a6a7f46-a39c-11e7-9d00-6b9853f42394.png)

**Comment by dodger487** [comment]
Yeah, I'd love to get it working that way as well but there are some
significant challenges to it, basically in terms of when Python and R want
to evaluate expressions.

Perhaps a "generate_uuid" or a more general "for_each_group" function might
be of value as a core part of the package.

Thank you for using the package and opening an issue!
